#!/usr/bin/env bash
# Weird... Weird task
FILE="school"
if [ -e $FILE ]; then
	printf "school file exists\n"
	if [ ! -s $FILE ]; then
		printf "school file is empty\n"
	else
		printf "school file is not empty\n"
	fi
	if [ -f $FILE ]; then
		printf "school is a regular file\n"
	fi
else
	printf "school file does not exist\n"
fi
