#!/usr/bin/env bash
# Weird... Weird task
FILE="school"
if [ -e $FILE ]; then
	printf "school file exists"
	if [ ! -s $FILE ]; then
		printf "school file is empty"
	else
		printf "school file is not empty"
	fi
	if [ -f $FILE ]; then
		printf "school is a regular file"
	fi
else
	printf "school file does not exist"
fi
