#!/usr/bin/env bash
# Hm
trmnt(){
	rm /var/run/myscript.pid
	exit
}
echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'trmnt' SIGQUIT
done
