#!/usr/bin/env bash
# Hm
PIDFILE="/var/run/holbertonscript.pid"
echo $$ > "$PIDFILE"

sigterm_handler() {
    echo "I hate the kill command"
    rm -f "$PIDFILE"
    exit 0
}

sigint_handler() {
    echo "Y U no love me?!"
}

sigquit_handler() {
    rm -f "$PIDFILE"
    exit 0
}
trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
